# Generated by Django 5.0.1 on 2024-04-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='price',
        ),
    ]
