# Generated by Django 5.0.1 on 2024-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0003_alter_django_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media\\images'),
        ),
    ]
