# Generated by Django 5.0.1 on 2024-04-25 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0004_alter_django_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='django',
            name='price',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='django',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
