# Generated by Django 5.0.1 on 2024-04-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0006_alter_django_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='price',
        ),
    ]
